awesome-tray.el
As title, add a module showing buffer name. 
Some screenshots:
dark theme:
light theme:
For my personal opinion, showing buffer name may be more useful than mode name, because we can easily judge the major mode from file extension in almost 80% cases, and some people are easily to forget the file name they are editing (for example, me), so I add this module to help others having same problem with me. 
BTW,  some colors cannot be loaded on my system,  I got this error message, 
Unable to load "SystemOrangeColor"
Unable to load "SystemPInkColor"
Unable to load "SystemGrayColor"
, they just display black on light theme and white on dark theme, which is fine for me so I haven't fix it.  I highly recommend you to test other colors for displaying buffer name if you decide to merge the PR.
=> Add buffer name module

README.md, awesome-tray.el
Solves https://github.com/manateelazycat/awesome-tray/issues/25. Besides, `cl-lib` is used instead of `cl`. `cl` is deprecated.
=> Use a declarative scheme to add modules.

README.md, awesome-tray.el
当 buffer 不是文件时，显示 buffer 名称，否则显示路径。路径过长时，一级以上的父目录会用首字母或 `...` 表示。
这个模块实现了 https://github.com/manateelazycat/awesome-tray/issues/26 中的想法。我认为我们应当尽量截短 awesome-tab 模块的信息。若用户关注文件所在的目录，可以选择使用 file-path 或 parent-dir。
这个补丁假设了 https://github.com/manateelazycat/awesome-tray/pull/27 已经被接收。请先 merge 那个，再 merge 这个。
=> Add file-path module.

awesome-tray.el
- Return `""` if buffer is not visiting a file (e.g. the \*scratch\* buffer)
- Show a `*` if buffer is modified since last save.
=> improve parent-dir module

README.md, awesome-tray.el
如题。此外刚刚不小心把另一个改动推到同一个分支了，那个是让以 `.` 开头的目录在 file-path 中保留两个字符，比如 `.emacs.d` 会缩短成 `.e`。
=> doc: Add information about each module.

README.md, awesome-tray.el
现在可以定制显示几级完整路径，显示几级截短的路径，截短到多短，以及是否显示文件名。事实上已经覆盖 parent-dir 了，除了显示风格不同：parent-dir 总是显示 `dir: dirname`，file-path 经过定制可以显示 `.../dirname/`。
=> improve file-path module.

awesome-tray.el
这个其实在 https://github.com/manateelazycat/awesome-tray/issues/18 中也提到了。但 `string-width` 总以为一个中文字符是 2 个单位宽的，所以只有在终端下、或使用严格半宽的西文字体时才正常。大多数情况下看上去是这样的，右边多一段空白：
但还是比原来有中文就会折行要好些。
因为 Emacs 并不能搞右对齐之类的东西，如果要完美的话我想唯一的方法是让用户指定一个 CJK 字符有多宽，在计算宽度时数一数有几个 CJK 字符再算，但是就太麻烦了。
=> fix: calculate string length using string-width

awesome-tray.el
截断时，当保留的字符数目大于目录名长度时无法显示 `file-path`。
具体原因参考 `substring` 函数的文档说明：
— Function: **substring** _string &optional start end_
An `args-out-of-range` error is signaled if _start_ indicates a character following _end_, or if either integer is out of range for _string_.
=> fix:error if the number of reserved characters is greater than the length of directory name

awesome-tray.el
Headers should have 3 `;`, according to the [guidelines](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html)
Related to [this issue](https://github.com/quelpa/quelpa-use-package/issues/14)
=> Header correction

awesome-tray.el
- Let the specification of a module omit its face, in which case none
is applied: that way, the info function can change the face on the
fly.
- When a string in awesome-tray-active-modules is not the name of a
registered module, show it verbatim (using a custom face): that way,
one can introduce extra separators or spaces, and also immediately see
if there's an unknown module there.
=> Allow empty face specs in modules and show literal constants

awesome-tray.el
I augmented `awesome-tray-module-alist` takes a function as the face of a module. This allows a module to have difference faces for different cases (e.g., `git-info` can be red when there is uncommitted files).
=> [new feature] allow modeline face depends on buffer status

awesome-tray.el
- Pass "" as FORMAT to `with-demoted-errors`
- Check `flymake--state`, it would cause error with `hash-table-keys` if it was `nil`
=> Fix flymake module

README.md, awesome-tray.el
the anzu code is from doom-modeline
anzu is enabling the modeline and the after-load block is actually useless
=> anzu: Fixed anzu enabling the modeline and removed useless code

awesome-tray.el
This gives an error when opening some specific buffers
=> git: Fixed `file-exists-p` taking nil as an argument

awesome-tray.el
当 emacs 以守护模式运行时，有一个看不到的 Frame 被创建，用 emacsclient 创建 Frame 后，(frame-list) 实际上会返回两个 frame，倒数第一个是看不到的 frame ，倒数第二个才是能看见的 main frame 
```
(#<frame Emacs 000002017a3a7f40> #<frame F1 00000201622388d0>)
```
=> get correct frame width when using daemon, fix #58

awesome-tray.el
Since MacOS Sierra 10.12.2, mac does not supply battery remaining time[1].
The `%t` in `battery-format` will be replaced with `N/A`.
Therefore, it might be reasonable to not show battery remaining time on MacOS.
[1] Emacs get battery status in `battery-status-function`, which uses `pmset` to get battery status:
```
((and (eq system-type 'darwin)
(ignore-errors
(with-temp-buffer
(and (eq (call-process "pmset" nil t nil "-g" "ps") 0)
(not (bobp))))))
#'battery-pmset)
```
On MacOS Ventura 13.2.1, this command will show:
```
> pmset -g ps
Now drawing from 'AC Power'
-InternalBattery-0 (id=7405667)	100%; charged; 0:00 remaining present: true
> pmset -g ps
Now drawing from 'Battery Power'
-InternalBattery-0 (id=7405667)	100%; discharging; (no estimate) present: true
```
No remaining time …
=> don't show battery remaining time on mac

README.md, awesome-tray-faces.el, awesome-tray.el
when it is in pdf-view-mode, location info is useless, so let's combine them with `location-or-page` module.
=> Combine location and pdf-view-page to save minibuffer space.

README.md, awesome-tray.el
If `current-input-method` is not Rime, awesome-tray still shows "ZH".
Changes in this PR:
- default no input-method indicator if no input method is toggled
- show "ZH" if current-input-method is in list `awesome-tray-input-method-local-methods`
- show `input-method-title` otherwise, such as "DE@" for German, "FR@" for French.
=> Globalized input method

awesome-tray.el
remove text properties, otherwise when mouse hovers to it, help echo will be shown in mini buffer.
=> Remove text properties from `celestial-mode-line-string'

README.md, awesome-tray.el
`awesome-tray-adjust-mode-line-color-enable`: 
Enabled by default. If non-nil, adjust mode-line  color when buffer state changes.
=> Make buffer state indicator configurable.

awesome-tray.el
Fix the issue where the 'awesome-tray-file-path-truncated-name-length' option was not functioning as expected.
=> Fix 'awesome-tray-file-path-truncated-name-length' option issue

awesome-tray.el
Add offset to avoid line wrap when aligned to the right:
1. Add 1 pixel if right fringe present and overflow-newline-into-fringe nil.
2. Add 1 char if no right fringe.
2. Add 1 char if in TUI.
If awesome-tray-info-padding-right is set to something else than 0 keep the old behavior.
I had a similar problem at https://github.com/emacs-sideline/sideline/issues/18
=> Fix right aligned line wrap.

awesome-tray.el
`set-text-properties` 不会返回string，根据message长度切换 essential-info 动作不正常。
=> fix the action switching essential info
